import { Opportunity, Status, Priority } from './types';
import { generateId } from './utils';

function daysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().split('T')[0];
}

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split('T')[0];
}

function dtAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

const BASE: Omit<Opportunity, 'id'> = {
  salesPersonName: '',
  dateEntered: daysAgo(30),
  dateNeeded: daysFromNow(30),
  targetPrice: null,
  annualVolume: null,
  quickNote: '',
  customerName: '',
  productName: '',
  productCategory: '',
  status: 'New',
  priority: 'Medium',
  completionPercent: 0,
  assignedOwner: '',
  supplierName: '',
  lastUpdated: new Date().toISOString(),
  nextAction: '',
  followUpDate: '',
  estimatedMargin: null,
  actualQuotedPrice: null,
  outcomeReason: '',
  internalComments: '',
  isCompleted: false,
  dateCompleted: '',
  includeInTodaysFocus: false,
  todaysFocusRank: 0,
  isSourcingRequest: false,
  requestedBy: '',
};

export const SEED_DATA: Opportunity[] = [
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'Mike Torres',
    dateEntered: daysAgo(14),
    dateNeeded: daysFromNow(5),
    targetPrice: 2.85,
    annualVolume: 120000,
    quickNote: 'Customer needs urgent pricing — competitor quoted $3.10',
    customerName: 'Acme Industrial',
    productName: '304 SS Hex Bolt M8x1.25',
    productCategory: 'Fasteners',
    status: 'Sourcing',
    priority: 'High',
    completionPercent: 40,
    assignedOwner: 'Mike Torres',
    supplierName: 'FastenPro USA',
    lastUpdated: dtAgo(1),
    nextAction: 'Get final quote from FastenPro by EOD',
    followUpDate: daysFromNow(1),
    estimatedMargin: 18,
    actualQuotedPrice: null,
    includeInTodaysFocus: true,
    todaysFocusRank: 1,
  },
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'Sarah Chen',
    dateEntered: daysAgo(7),
    dateNeeded: daysFromNow(12),
    targetPrice: 0.45,
    annualVolume: 500000,
    quickNote: 'High volume — must beat current supplier by 10%',
    customerName: 'NovaTech Electronics',
    productName: 'M3 Pan Head Screw Zinc',
    productCategory: 'Fasteners',
    status: 'Waiting on Supplier',
    priority: 'High',
    completionPercent: 55,
    assignedOwner: 'Sarah Chen',
    supplierName: 'Global Fastener Co',
    lastUpdated: dtAgo(2),
    nextAction: 'Follow up with Global Fastener on sample delivery',
    followUpDate: daysFromNow(2),
    estimatedMargin: 22,
    actualQuotedPrice: null,
    includeInTodaysFocus: true,
    todaysFocusRank: 2,
  },
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'Mike Torres',
    dateEntered: daysAgo(21),
    dateNeeded: daysFromNow(2),
    targetPrice: 14.50,
    annualVolume: 8000,
    quickNote: 'Overdue review — customer is waiting on final quote',
    customerName: 'Precision Parts LLC',
    productName: 'Aluminum Standoff 10mm',
    productCategory: 'Components',
    status: 'Quoted',
    priority: 'High',
    completionPercent: 75,
    assignedOwner: 'Mike Torres',
    supplierName: 'AlumaCraft',
    lastUpdated: dtAgo(3),
    nextAction: 'Send formal quote to purchasing department',
    followUpDate: daysFromNow(1),
    estimatedMargin: 15,
    actualQuotedPrice: 15.20,
    includeInTodaysFocus: true,
    todaysFocusRank: 3,
  },
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'Jennifer Walsh',
    dateEntered: daysAgo(5),
    dateNeeded: daysFromNow(20),
    targetPrice: 3200,
    annualVolume: 50,
    quickNote: 'Custom spec — need drawings from customer first',
    customerName: 'MidWest Auto',
    productName: 'Custom Bracket Assembly',
    productCategory: 'Assemblies',
    status: 'In Review',
    priority: 'Medium',
    completionPercent: 20,
    assignedOwner: 'Jennifer Walsh',
    supplierName: '',
    lastUpdated: dtAgo(1),
    nextAction: 'Request engineering drawings from customer',
    followUpDate: daysFromNow(3),
    estimatedMargin: 28,
    actualQuotedPrice: null,
    includeInTodaysFocus: false,
    todaysFocusRank: 0,
  },
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'Sarah Chen',
    dateEntered: daysAgo(45),
    dateNeeded: daysAgo(10),
    targetPrice: 0.89,
    annualVolume: 250000,
    quickNote: 'Won! Contract signed last week.',
    customerName: 'Apex Manufacturing',
    productName: '316 SS Washer 1/4"',
    productCategory: 'Fasteners',
    status: 'Won',
    priority: 'Medium',
    completionPercent: 100,
    assignedOwner: 'Sarah Chen',
    supplierName: 'SteelMaster Inc',
    lastUpdated: dtAgo(7),
    nextAction: 'Confirm first shipment date',
    followUpDate: daysFromNow(5),
    estimatedMargin: 20,
    actualQuotedPrice: 0.95,
    isCompleted: true,
    dateCompleted: daysAgo(7),
    outcomeReason: 'Beat competitor on price and lead time',
    includeInTodaysFocus: false,
    todaysFocusRank: 0,
  },
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'David Kim',
    dateEntered: daysAgo(10),
    dateNeeded: daysFromNow(30),
    targetPrice: 1850,
    annualVolume: 24,
    quickNote: 'New prospect — referred by Apex',
    customerName: 'Summit Engineering',
    productName: 'Hydraulic Manifold Block',
    productCategory: 'Components',
    status: 'New',
    priority: 'Medium',
    completionPercent: 10,
    assignedOwner: 'David Kim',
    supplierName: '',
    lastUpdated: dtAgo(4),
    nextAction: 'Schedule discovery call with engineering team',
    followUpDate: daysFromNow(4),
    estimatedMargin: null,
    actualQuotedPrice: null,
    includeInTodaysFocus: false,
    todaysFocusRank: 0,
  },
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'Mike Torres',
    dateEntered: daysAgo(60),
    dateNeeded: daysAgo(15),
    targetPrice: 12.75,
    annualVolume: 15000,
    quickNote: 'Lost on price. Customer went with overseas supplier.',
    customerName: 'Rocket Plastics',
    productName: 'Nylon Insert Nut M10',
    productCategory: 'Fasteners',
    status: 'Lost',
    priority: 'Low',
    completionPercent: 100,
    assignedOwner: 'Mike Torres',
    supplierName: 'PolyTech',
    lastUpdated: dtAgo(15),
    nextAction: '',
    followUpDate: '',
    estimatedMargin: 12,
    actualQuotedPrice: 13.50,
    isCompleted: true,
    dateCompleted: daysAgo(15),
    outcomeReason: 'Price too high — overseas competitor at $9.20',
    includeInTodaysFocus: false,
    todaysFocusRank: 0,
  },
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'Jennifer Walsh',
    dateEntered: daysAgo(3),
    dateNeeded: daysFromNow(45),
    targetPrice: 0.22,
    annualVolume: 2000000,
    quickNote: 'Massive volume opportunity — needs VP approval before quoting',
    customerName: 'Global Auto Parts',
    productName: 'M5 Socket Cap Screw Black Oxide',
    productCategory: 'Fasteners',
    status: 'In Review',
    priority: 'High',
    completionPercent: 15,
    assignedOwner: 'Jennifer Walsh',
    supplierName: 'Precision Fasteners Inc',
    lastUpdated: dtAgo(1),
    nextAction: 'Present to VP for pricing approval',
    followUpDate: daysFromNow(2),
    estimatedMargin: 16,
    actualQuotedPrice: null,
    includeInTodaysFocus: true,
    todaysFocusRank: 4,
  },
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'David Kim',
    dateEntered: daysAgo(30),
    dateNeeded: daysFromNow(8),
    targetPrice: 4.10,
    annualVolume: 75000,
    quickNote: 'Customer threatened to go elsewhere if no quote by Friday',
    customerName: 'BlueStar Electrical',
    productName: 'Cable Tie Mounts Nylon',
    productCategory: 'Plastics',
    status: 'Sourcing',
    priority: 'High',
    completionPercent: 50,
    assignedOwner: 'David Kim',
    supplierName: 'PolySource',
    lastUpdated: dtAgo(2),
    nextAction: 'Get updated pricing from PolySource',
    followUpDate: daysFromNow(1),
    estimatedMargin: 24,
    actualQuotedPrice: null,
    includeInTodaysFocus: false,
    todaysFocusRank: 0,
  },
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'Sarah Chen',
    dateEntered: daysAgo(20),
    dateNeeded: daysFromNow(25),
    targetPrice: 88.00,
    annualVolume: 300,
    quickNote: 'On hold pending budget approval from customer',
    customerName: 'Fusion Labs',
    productName: 'Aluminum Enclosure 4x6x2',
    productCategory: 'Metals',
    status: 'On Hold',
    priority: 'Low',
    completionPercent: 30,
    assignedOwner: 'Sarah Chen',
    supplierName: 'MetalFab Direct',
    lastUpdated: dtAgo(5),
    nextAction: 'Check in with buyer next month',
    followUpDate: daysFromNow(14),
    estimatedMargin: 19,
    actualQuotedPrice: 92.50,
    includeInTodaysFocus: false,
    todaysFocusRank: 0,
  },
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'Mike Torres',
    dateEntered: daysAgo(4),
    dateNeeded: daysFromNow(18),
    targetPrice: 6.75,
    annualVolume: 40000,
    quickNote: 'Requires RoHS compliance cert',
    customerName: 'TechVision Corp',
    productName: 'PCB Standoff M2.5 Brass',
    productCategory: 'Electronics',
    status: 'Sourcing',
    priority: 'Medium',
    completionPercent: 25,
    assignedOwner: 'Mike Torres',
    supplierName: 'ElectraSource',
    lastUpdated: dtAgo(1),
    nextAction: 'Confirm RoHS compliance with supplier',
    followUpDate: daysFromNow(3),
    estimatedMargin: 21,
    actualQuotedPrice: null,
    includeInTodaysFocus: false,
    todaysFocusRank: 0,
  },
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'Jennifer Walsh',
    dateEntered: daysAgo(8),
    dateNeeded: daysFromNow(35),
    targetPrice: 155.00,
    annualVolume: 120,
    quickNote: 'Existing customer expansion — smooth close expected',
    customerName: 'Apex Manufacturing',
    productName: 'Precision Ground Shaft 1" Dia',
    productCategory: 'Metals',
    status: 'Awaiting Customer Response',
    priority: 'Medium',
    completionPercent: 80,
    assignedOwner: 'Jennifer Walsh',
    supplierName: 'BarStock Direct',
    lastUpdated: dtAgo(3),
    nextAction: 'Follow up if no response by Thursday',
    followUpDate: daysFromNow(4),
    estimatedMargin: 23,
    actualQuotedPrice: 162.00,
    includeInTodaysFocus: false,
    todaysFocusRank: 0,
  },
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'David Kim',
    dateEntered: daysAgo(2),
    dateNeeded: daysFromNow(60),
    targetPrice: 0.08,
    annualVolume: 5000000,
    quickNote: 'Giant opportunity — need to verify volume before investing time',
    customerName: 'NovaTech Electronics',
    productName: 'Micro Rivet 1/8" Aluminum',
    productCategory: 'Fasteners',
    status: 'New',
    priority: 'High',
    completionPercent: 5,
    assignedOwner: 'David Kim',
    supplierName: '',
    lastUpdated: dtAgo(1),
    nextAction: 'Verify annual volume with purchasing manager',
    followUpDate: daysFromNow(2),
    estimatedMargin: null,
    actualQuotedPrice: null,
    includeInTodaysFocus: false,
    todaysFocusRank: 0,
  },
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'Sarah Chen',
    dateEntered: daysAgo(35),
    dateNeeded: daysAgo(5),
    targetPrice: 22.50,
    annualVolume: 3600,
    quickNote: 'OVERDUE — no response to last 2 follow-ups',
    customerName: 'HydroTech Systems',
    productName: 'O-Ring Kit EPDM 50pc',
    productCategory: 'Raw Materials',
    status: 'Awaiting Customer Response',
    priority: 'High',
    completionPercent: 70,
    assignedOwner: 'Sarah Chen',
    supplierName: 'SealTech USA',
    lastUpdated: dtAgo(8),
    nextAction: 'Escalate to manager contact — customer not responding',
    followUpDate: daysFromNow(1),
    estimatedMargin: 26,
    actualQuotedPrice: 24.00,
    includeInTodaysFocus: false,
    todaysFocusRank: 0,
  },
  {
    ...BASE,
    id: generateId(),
    salesPersonName: 'Mike Torres',
    dateEntered: daysAgo(50),
    dateNeeded: daysAgo(20),
    targetPrice: 5600,
    annualVolume: 12,
    quickNote: 'Completed — delivered on time and on budget',
    customerName: 'Summit Engineering',
    productName: 'CNC Machined Housing Alum',
    productCategory: 'Metals',
    status: 'Completed',
    priority: 'Low',
    completionPercent: 100,
    assignedOwner: 'Mike Torres',
    supplierName: 'PrecisionCNC',
    lastUpdated: dtAgo(20),
    nextAction: '',
    followUpDate: '',
    estimatedMargin: 17,
    actualQuotedPrice: 5800,
    isCompleted: true,
    dateCompleted: daysAgo(20),
    outcomeReason: 'Customer satisfied — potential repeat order',
    internalComments: 'Great execution. Ask for referral.',
    includeInTodaysFocus: false,
    todaysFocusRank: 0,
  },
];
